services:
  bot-1:
    build: ./
    platform: linux/amd64
    container_name: zoom-bot-1
    volumes:
     - .:/tmp/meeting-sdk-linux-sample
     - build-cache:/tmp/meeting-sdk-linux-sample/build
    environment:
     - DISPLAY_NAME=Bot-1-Alice
     - JOIN_URL=https://us05web.zoom.us/j/5067498331?pwd=4aJ3z9zb8f0ZaKiouEYdWNFhBh1V6d.1&omn=86931044022
     - CLIENT_ID=vdPX1q2bSQKip0X17LqXAw
     - CLIENT_SECRET=Te1YdXaBL6IScwdBVlNF0kay75KDMkyz
     - QT_LOGGING_RULES=*.debug=false;*.warning=false;*.info=false;*.critical=false
     - QT_QPA_PLATFORM=offscreen
     - G_MESSAGES_DEBUG=
    entrypoint: ["/tini", "--", "./bin/entry-bot-optimized.sh"]
    command:
      - "--client-id"
      - "vdPX1q2bSQKip0X17LqXAw"
      - "--client-secret"
      - "Te1YdXaBL6IScwdBVlNF0kay75KDMkyz"
      - "--join-url"
      - "https://us05web.zoom.us/j/5067498331?pwd=4aJ3z9zb8f0ZaKiouEYdWNFhBh1V6d.1&omn=86931044022"
      - "--display-name"
      - "Bot-1-Alice"
      - "--config"
      - "config.toml"
      - "RawVideo"
      - "--input"
      - "input-video.mp4"
    deploy:
      resources:
        limits:
          cpus: '0.6'      # Optimized: was 1.0, actual usage ~0.5
          memory: 256M     # Optimized: was 2G, actual usage ~128MB
        reservations:
          cpus: '0.1'      # Optimized: was 0.2
          memory: 128M     # Optimized: was 512M
    restart: no

  bot-2:
    build: ./
    platform: linux/amd64
    container_name: zoom-bot-2
    volumes:
     - .:/tmp/meeting-sdk-linux-sample
     - build-cache:/tmp/meeting-sdk-linux-sample/build
    environment:
     - DISPLAY_NAME=Bot-2-Bob
     - JOIN_URL=https://us05web.zoom.us/j/5067498331?pwd=4aJ3z9zb8f0ZaKiouEYdWNFhBh1V6d.1&omn=86931044022
     - CLIENT_ID=vdPX1q2bSQKip0X17LqXAw
     - CLIENT_SECRET=Te1YdXaBL6IScwdBVlNF0kay75KDMkyz
     - QT_LOGGING_RULES=*.debug=false;*.warning=false;*.info=false;*.critical=false
     - QT_QPA_PLATFORM=offscreen
     - G_MESSAGES_DEBUG=
    entrypoint: ["/tini", "--", "./bin/entry-bot-optimized.sh"]
    command:
      - "--client-id"
      - "vdPX1q2bSQKip0X17LqXAw"
      - "--client-secret"
      - "Te1YdXaBL6IScwdBVlNF0kay75KDMkyz"
      - "--join-url"
      - "https://us05web.zoom.us/j/5067498331?pwd=4aJ3z9zb8f0ZaKiouEYdWNFhBh1V6d.1&omn=86931044022"
      - "--display-name"
      - "Bot-2-Bob"
      - "--config"
      - "config.toml"
      - "RawVideo"
      - "--input"
      - "input-video.mp4"
    deploy:
      resources:
        limits:
          cpus: '0.6'      # Optimized: was 1.0, actual usage ~0.5
          memory: 256M     # Optimized: was 2G, actual usage ~128MB
        reservations:
          cpus: '0.1'      # Optimized: was 0.2
          memory: 128M     # Optimized: was 512M
    restart: no

  bot-3:
    build: ./
    platform: linux/amd64
    container_name: zoom-bot-3
    volumes:
     - .:/tmp/meeting-sdk-linux-sample
     - build-cache:/tmp/meeting-sdk-linux-sample/build
    environment:
     - DISPLAY_NAME=Bot-3-Charlie
     - JOIN_URL=https://us05web.zoom.us/j/5067498331?pwd=4aJ3z9zb8f0ZaKiouEYdWNFhBh1V6d.1&omn=86931044022
     - CLIENT_ID=vdPX1q2bSQKip0X17LqXAw
     - CLIENT_SECRET=Te1YdXaBL6IScwdBVlNF0kay75KDMkyz
     - QT_LOGGING_RULES=*.debug=false;*.warning=false;*.info=false;*.critical=false
     - QT_QPA_PLATFORM=offscreen
     - G_MESSAGES_DEBUG=
    entrypoint: ["/tini", "--", "./bin/entry-bot-optimized.sh"]
    command:
      - "--client-id"
      - "vdPX1q2bSQKip0X17LqXAw"
      - "--client-secret"
      - "Te1YdXaBL6IScwdBVlNF0kay75KDMkyz"
      - "--join-url"
      - "https://us05web.zoom.us/j/5067498331?pwd=4aJ3z9zb8f0ZaKiouEYdWNFhBh1V6d.1&omn=86931044022"
      - "--display-name"
      - "Bot-3-Charlie"
      - "--config"
      - "config.toml"
      - "RawVideo"
      - "--input"
      - "input-video.mp4"
    deploy:
      resources:
        limits:
          cpus: '0.6'      # Optimized: was 1.0, actual usage ~0.5
          memory: 256M     # Optimized: was 2G, actual usage ~128MB
        reservations:
          cpus: '0.1'      # Optimized: was 0.2
          memory: 128M     # Optimized: was 512M
    restart: no

  bot-4:
    build: ./
    platform: linux/amd64
    container_name: zoom-bot-4
    volumes:
     - .:/tmp/meeting-sdk-linux-sample
     - build-cache:/tmp/meeting-sdk-linux-sample/build
    environment:
     - DISPLAY_NAME=Bot-4-Diana
     - JOIN_URL=https://us05web.zoom.us/j/5067498331?pwd=4aJ3z9zb8f0ZaKiouEYdWNFhBh1V6d.1&omn=86931044022
     - CLIENT_ID=vdPX1q2bSQKip0X17LqXAw
     - CLIENT_SECRET=Te1YdXaBL6IScwdBVlNF0kay75KDMkyz
     - QT_LOGGING_RULES=*.debug=false;*.warning=false;*.info=false;*.critical=false
     - QT_QPA_PLATFORM=offscreen
     - G_MESSAGES_DEBUG=
    entrypoint: ["/tini", "--", "./bin/entry-bot-optimized.sh"]
    command:
      - "--client-id"
      - "vdPX1q2bSQKip0X17LqXAw"
      - "--client-secret"
      - "Te1YdXaBL6IScwdBVlNF0kay75KDMkyz"
      - "--join-url"
      - "https://us05web.zoom.us/j/5067498331?pwd=4aJ3z9zb8f0ZaKiouEYdWNFhBh1V6d.1&omn=86931044022"
      - "--display-name"
      - "Bot-4-Diana"
      - "--config"
      - "config.toml"
      - "RawVideo"
      - "--input"
      - "input-video.mp4"
    deploy:
      resources:
        limits:
          cpus: '0.6'      # Optimized: was 1.0, actual usage ~0.5
          memory: 256M     # Optimized: was 2G, actual usage ~128MB
        reservations:
          cpus: '0.1'      # Optimized: was 0.2
          memory: 128M     # Optimized: was 512M
    restart: no

  bot-5:
    build: ./
    platform: linux/amd64
    container_name: zoom-bot-5
    volumes:
     - .:/tmp/meeting-sdk-linux-sample
     - build-cache:/tmp/meeting-sdk-linux-sample/build
    environment:
     - DISPLAY_NAME=Bot-5-Eve
     - JOIN_URL=https://us05web.zoom.us/j/5067498331?pwd=4aJ3z9zb8f0ZaKiouEYdWNFhBh1V6d.1&omn=86931044022
     - CLIENT_ID=vdPX1q2bSQKip0X17LqXAw
     - CLIENT_SECRET=Te1YdXaBL6IScwdBVlNF0kay75KDMkyz
     - QT_LOGGING_RULES=*.debug=false;*.warning=false;*.info=false;*.critical=false
     - QT_QPA_PLATFORM=offscreen
     - G_MESSAGES_DEBUG=
    entrypoint: ["/tini", "--", "./bin/entry-bot-optimized.sh"]
    command:
      - "--client-id"
      - "vdPX1q2bSQKip0X17LqXAw"
      - "--client-secret"
      - "Te1YdXaBL6IScwdBVlNF0kay75KDMkyz"
      - "--join-url"
      - "https://us05web.zoom.us/j/5067498331?pwd=4aJ3z9zb8f0ZaKiouEYdWNFhBh1V6d.1&omn=86931044022"
      - "--display-name"
      - "Bot-5-Eve"
      - "--config"
      - "config.toml"
      - "RawVideo"
      - "--input"
      - "input-video.mp4"
    deploy:
      resources:
        limits:
          cpus: '0.6'      # Optimized: was 1.0, actual usage ~0.5
          memory: 256M     # Optimized: was 2G, actual usage ~128MB
        reservations:
          cpus: '0.1'      # Optimized: was 0.2
          memory: 128M     # Optimized: was 512M
    restart: no

  bot-6:
    build: ./
    platform: linux/amd64
    container_name: zoom-bot-6
    volumes:
     - .:/tmp/meeting-sdk-linux-sample
     - build-cache:/tmp/meeting-sdk-linux-sample/build
    environment:
     - DISPLAY_NAME=Bot-6-Frank
     - JOIN_URL=https://us05web.zoom.us/j/5067498331?pwd=4aJ3z9zb8f0ZaKiouEYdWNFhBh1V6d.1&omn=86931044022
     - CLIENT_ID=vdPX1q2bSQKip0X17LqXAw
     - CLIENT_SECRET=Te1YdXaBL6IScwdBVlNF0kay75KDMkyz
     - QT_LOGGING_RULES=*.debug=false;*.warning=false;*.info=false;*.critical=false
     - QT_QPA_PLATFORM=offscreen
     - G_MESSAGES_DEBUG=
    entrypoint: ["/tini", "--", "./bin/entry-bot-optimized.sh"]
    command:
      - "--client-id"
      - "vdPX1q2bSQKip0X17LqXAw"
      - "--client-secret"
      - "Te1YdXaBL6IScwdBVlNF0kay75KDMkyz"
      - "--join-url"
      - "https://us05web.zoom.us/j/5067498331?pwd=4aJ3z9zb8f0ZaKiouEYdWNFhBh1V6d.1&omn=86931044022"
      - "--display-name"
      - "Bot-6-Frank"
      - "--config"
      - "config.toml"
      - "RawVideo"
      - "--input"
      - "input-video.mp4"
    deploy:
      resources:
        limits:
          cpus: '0.6'      # Optimized: was 1.0, actual usage ~0.5
          memory: 256M     # Optimized: was 2G, actual usage ~128MB
        reservations:
          cpus: '0.1'      # Optimized: was 0.2
          memory: 128M     # Optimized: was 512M
    restart: no

  bot-7:
    build: ./
    platform: linux/amd64
    container_name: zoom-bot-7
    volumes:
     - .:/tmp/meeting-sdk-linux-sample
     - build-cache:/tmp/meeting-sdk-linux-sample/build
    environment:
     - DISPLAY_NAME=Bot-7-Grace
     - JOIN_URL=https://us05web.zoom.us/j/5067498331?pwd=4aJ3z9zb8f0ZaKiouEYdWNFhBh1V6d.1&omn=86931044022
     - CLIENT_ID=vdPX1q2bSQKip0X17LqXAw
     - CLIENT_SECRET=Te1YdXaBL6IScwdBVlNF0kay75KDMkyz
     - QT_LOGGING_RULES=*.debug=false;*.warning=false;*.info=false;*.critical=false
     - QT_QPA_PLATFORM=offscreen
     - G_MESSAGES_DEBUG=
    entrypoint: ["/tini", "--", "./bin/entry-bot-optimized.sh"]
    command:
      - "--client-id"
      - "vdPX1q2bSQKip0X17LqXAw"
      - "--client-secret"
      - "Te1YdXaBL6IScwdBVlNF0kay75KDMkyz"
      - "--join-url"
      - "https://us05web.zoom.us/j/5067498331?pwd=4aJ3z9zb8f0ZaKiouEYdWNFhBh1V6d.1&omn=86931044022"
      - "--display-name"
      - "Bot-7-Grace"
      - "--config"
      - "config.toml"
      - "RawVideo"
      - "--input"
      - "input-video.mp4"
    deploy:
      resources:
        limits:
          cpus: '0.6'      # Optimized: was 1.0, actual usage ~0.5
          memory: 256M     # Optimized: was 2G, actual usage ~128MB
        reservations:
          cpus: '0.1'      # Optimized: was 0.2
          memory: 128M     # Optimized: was 512M
    restart: no

  bot-8:
    build: ./
    platform: linux/amd64
    container_name: zoom-bot-8
    volumes:
     - .:/tmp/meeting-sdk-linux-sample
     - build-cache:/tmp/meeting-sdk-linux-sample/build
    environment:
     - DISPLAY_NAME=Bot-8-Henry
     - JOIN_URL=https://us05web.zoom.us/j/5067498331?pwd=4aJ3z9zb8f0ZaKiouEYdWNFhBh1V6d.1&omn=86931044022
     - CLIENT_ID=vdPX1q2bSQKip0X17LqXAw
     - CLIENT_SECRET=Te1YdXaBL6IScwdBVlNF0kay75KDMkyz
     - QT_LOGGING_RULES=*.debug=false;*.warning=false;*.info=false;*.critical=false
     - QT_QPA_PLATFORM=offscreen
     - G_MESSAGES_DEBUG=
    entrypoint: ["/tini", "--", "./bin/entry-bot-optimized.sh"]
    command:
      - "--client-id"
      - "vdPX1q2bSQKip0X17LqXAw"
      - "--client-secret"
      - "Te1YdXaBL6IScwdBVlNF0kay75KDMkyz"
      - "--join-url"
      - "https://us05web.zoom.us/j/5067498331?pwd=4aJ3z9zb8f0ZaKiouEYdWNFhBh1V6d.1&omn=86931044022"
      - "--display-name"
      - "Bot-8-Henry"
      - "--config"
      - "config.toml"
      - "RawVideo"
      - "--input"
      - "input-video.mp4"
    deploy:
      resources:
        limits:
          cpus: '0.6'      # Optimized: was 1.0, actual usage ~0.5
          memory: 256M     # Optimized: was 2G, actual usage ~128MB
        reservations:
          cpus: '0.1'      # Optimized: was 0.2
          memory: 128M     # Optimized: was 512M
    restart: no

  bot-9:
    build: ./
    platform: linux/amd64
    container_name: zoom-bot-9
    volumes:
     - .:/tmp/meeting-sdk-linux-sample
     - build-cache:/tmp/meeting-sdk-linux-sample/build
    environment:
     - DISPLAY_NAME=Bot-9-Iris
     - JOIN_URL=https://us05web.zoom.us/j/5067498331?pwd=4aJ3z9zb8f0ZaKiouEYdWNFhBh1V6d.1&omn=86931044022
     - CLIENT_ID=vdPX1q2bSQKip0X17LqXAw
     - CLIENT_SECRET=Te1YdXaBL6IScwdBVlNF0kay75KDMkyz
     - QT_LOGGING_RULES=*.debug=false;*.warning=false;*.info=false;*.critical=false
     - QT_QPA_PLATFORM=offscreen
     - G_MESSAGES_DEBUG=
    entrypoint: ["/tini", "--", "./bin/entry-bot-optimized.sh"]
    command:
      - "--client-id"
      - "vdPX1q2bSQKip0X17LqXAw"
      - "--client-secret"
      - "Te1YdXaBL6IScwdBVlNF0kay75KDMkyz"
      - "--join-url"
      - "https://us05web.zoom.us/j/5067498331?pwd=4aJ3z9zb8f0ZaKiouEYdWNFhBh1V6d.1&omn=86931044022"
      - "--display-name"
      - "Bot-9-Iris"
      - "--config"
      - "config.toml"
      - "RawVideo"
      - "--input"
      - "input-video.mp4"
    deploy:
      resources:
        limits:
          cpus: '0.6'      # Optimized: was 1.0, actual usage ~0.5
          memory: 256M     # Optimized: was 2G, actual usage ~128MB
        reservations:
          cpus: '0.1'      # Optimized: was 0.2
          memory: 128M     # Optimized: was 512M
    restart: no

  bot-10:
    build: ./
    platform: linux/amd64
    container_name: zoom-bot-10
    volumes:
     - .:/tmp/meeting-sdk-linux-sample
     - build-cache:/tmp/meeting-sdk-linux-sample/build
    environment:
     - DISPLAY_NAME=Bot-10-Jack
     - JOIN_URL=https://us05web.zoom.us/j/5067498331?pwd=4aJ3z9zb8f0ZaKiouEYdWNFhBh1V6d.1&omn=86931044022
     - CLIENT_ID=vdPX1q2bSQKip0X17LqXAw
     - CLIENT_SECRET=Te1YdXaBL6IScwdBVlNF0kay75KDMkyz
     - QT_LOGGING_RULES=*.debug=false;*.warning=false;*.info=false;*.critical=false
     - QT_QPA_PLATFORM=offscreen
     - G_MESSAGES_DEBUG=
    entrypoint: ["/tini", "--", "./bin/entry-bot-optimized.sh"]
    command:
      - "--client-id"
      - "vdPX1q2bSQKip0X17LqXAw"
      - "--client-secret"
      - "Te1YdXaBL6IScwdBVlNF0kay75KDMkyz"
      - "--join-url"
      - "https://us05web.zoom.us/j/5067498331?pwd=4aJ3z9zb8f0ZaKiouEYdWNFhBh1V6d.1&omn=86931044022"
      - "--display-name"
      - "Bot-10-Jack"
      - "--config"
      - "config.toml"
      - "RawVideo"
      - "--input"
      - "input-video.mp4"
    deploy:
      resources:
        limits:
          cpus: '0.6'      # Optimized: was 1.0, actual usage ~0.5
          memory: 256M     # Optimized: was 2G, actual usage ~128MB
        reservations:
          cpus: '0.1'      # Optimized: was 0.2
          memory: 128M     # Optimized: was 512M
    restart: no

volumes:
  build-cache:
